# Generated by Django 3.1.6 on 2021-10-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stonewall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
    ]
