# Generated by Django 3.1.6 on 2021-10-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonewall', '0003_blogmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
