# Generated by Django 3.1.6 on 2021-11-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonewall', '0005_auto_20211112_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(upload_to='static/blog'),
        ),
    ]
